spring:
  datasource:
    username: root
    password: hemanth28114@bp
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver  # Corrected driver class
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    basic:
      enabled: false  # Disabling default security
